name: "Tests"
on:
  pull_request:
  push:
    branches:
      - main
      - "releases/*"

jobs:
  tests:
    name: "Integration testing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Run tests"
        run: docker compose run iot-agent-sdk-test
